추천 > 큰 가방 부분 설명 보충
krta2/awesome-nonsan pull request #11
Opened 2019-06-05 16:16 UTC by KimGenius

## 요약
- 큰 가방이 없거나 캐리어를 안들고가고 일반 가방 하나만 들고 갈시에 (심지어 쇼핑백도 구매를 안할시) 수료 후 집까지 머나먼 길을 양손 가득히 들고갈 수 있어 이 부분을 보충함
- 추후 누군가 훈련소에서 수료 후 가져오는 물품들을 상세하게 적어주면 좋겠습니다.

## 출처
- 2019년 4월 / 산업기능요원

2021-01-01 06:55 UTC, krta2 requested changes
리뷰가 늦었네요. 감사합니다!

2021-01-01 06:55 UTC, krta2 commented on README.md
> +  - 퇴소 전 쇼핑백 구매 기회를 주기 때문에 반드시 가져가진 않아도 됨 (단순히 가방 하나만 들고 가서 이 쇼핑백을 안산다면 수료 후 양손 가득 산타클로스 체험 가능)
```suggestion
  - 퇴소 전 쇼핑백 구매 기회를 주기 때문에 반드시 가져가진 않아도 됨(가져간 가방이 크지 않다면 구매하는 것 추천)
```

2021-01-01 06:55 UTC, krta2 commented on README.md
> +  - 퇴소 시 짐이 생각보다 많음 (전투화, 전투복, 생활화 등등)
```suggestion
  - 퇴소 시 짐이 생각보다 많음(전투화, 전투복, 생활화 등)
```

2021-01-01 06:55 UTC, krta2 commented on README.md
> +- 큰 가방 (또는 캐리어)
```suggestion
- 큰 가방 또는 캐리어
```

2021-01-01 06:56 UTC, krta2 commented
사소한 request changes 라 제가 적용하고 머지하겠습니다. 감사합니다.

2021-01-01 06:57 UTC, krta2 approved these changes

2021-01-01 06:58 UTC, merged

2021-01-17 12:39 UTC, KimGenius commented
앗 제가 하도 오래되서 신경을 안쓰다가 이제야 봤네요
감사합니다 :)