Add some infos
krta2/awesome-nonsan pull request #15
Opened 2020-12-03 12:19 UTC by yuyaebean

## 요약
- 코로나 시즌 및 최신 정보 업뎃

## 출처
- 2020년 12월 n사단 신교대

2021-01-01 06:52 UTC, krta2 requested changes
오랜만의 PR 이네요! 감사합니다.

2021-01-01 06:52 UTC, krta2 commented on README.md
> +	- 그 외에는 보급으로 다 나옴 (2020. 12. 정보)
위에서 현재는 보금으로 나오는 항목들을 삭제하는게 더 좋을거 같아요!

2021-01-01 06:52 UTC, krta2 commented on README.md
> +- 마스크 (코로나 기간 정보임)
```suggestion
- 마스크 (코로나19 기간 정보)
```

2021-01-03 04:04 UTC, soultree-fly commented on README.md
> +	- 그 외에는 보급으로 다 나옴 (2020. 12. 정보)
오 좋은 아이디어입니다 👍

2022-01-14 17:08 UTC, krta2 commented on README.md
> +  - 수신자 부담 전화를 본인 부담으로 바꿔서 가능 (수신자가 수신 허가 해주는 시간 절약 가능)
```suggestion
  - 수신자 부담 전화를 본인 부담으로 바꿔서 가능(수신자가 수신 허가 해주는 시간 절약 가능)
```

2022-01-14 17:08 UTC, krta2 commented on README.md
> +	- 샴푸, 바디워시는 올인원으로 가져가는걸 추천 (보급은 비누만 줌)
```suggestion
	- 샴푸, 바디워시는 올인원으로 가져가는걸 추천
```

2022-01-14 17:08 UTC, krta2 commented on README.md
> +  - 총기 손질, 위장 지울 때 빛을 발함 (위장 지우는 용으로는 클렌징 티슈를 좀 더 추천)
```suggestion
  - 총기 손질, 위장 지울 때 빛을 발함(위장 지우는 용으로는 클렌징 티슈를 좀 더 추천)
```

2022-01-14 17:10 UTC, krta2 approved these changes
제가 이 PR 은 왜 이제야 머지하는지 모르겠네요 😅 
마스크 관련해서는 업데이트된 내용이 이미 반영되어서 수정했습니다.
감사합니다 🙏

2022-01-14 17:10 UTC, merged