인터넷 편지 뉴스레터 서비스 추가
krta2/awesome-nonsan pull request #17
Opened 2021-07-27 12:18 UTC by lopun

## 요약
- 어떤 것을 했는지 간단하게 기술하세요.
- ex) 사격 훈련 팁을 추가함
- 요즘 핫한 인터넷 편지 뉴스레터 서비스를 추가했습니다.
- 주변에 도움이 됐다는 사람이 많아서 awesome-nonsan에도 추가하면 좋을 것 같아 PR 올립니다 🙏 

## 출처
- 훈련을 받은 날짜와 복무형태를 적어주세요.
- ex) 2019년 4월 / 산업기능요원
- 2021년 2월 / 산업기능요원

2021-07-29 08:10 UTC, krta2 requested changes

2021-07-29 08:10 UTC, krta2 commented on README.md
> +- [훈련소 인터넷편지 뉴스레터 서비스(인편허니)](https://armyhoney.com/)
@lopun 좋네요! 다만 준비물 보다는 팁에 가까운거 같아서 [#팁 - #연락] 에 적어주시면 더 좋을거 같아요 :)

2021-08-08 01:09 UTC, lopun commented on README.md
> +- [훈련소 인터넷편지 뉴스레터 서비스(인편허니)](https://armyhoney.com/)
@krta2 수정 완료했습니다! 그리고 awesome-nonsan 전용 할인정보도 추가해놓았습니다 :)

2021-08-08 07:39 UTC, krta2 approved these changes

2021-08-08 07:40 UTC, merged